#MF_Axon_Count_1.0
#Giger Laboratory
#Matthew Finneran

#Load necessary packages to run code.
library("EBImage")
library("magick")
library("ggplot2")
library("writexl")

#Load pre-processed tif image into R (refer to manuscript methods for pre-processing).
img <- readImage('Optic_Nerve_1.tif')

#Create a name for the image.
title <- 'Optic_Nerve_1'

#Slightly blur the CTB signal to make more continuous for better object identification and then plot.
img_blur <- gblur(img, sigma = 5)
plot(img_blur)

#Create mask of image generated by foreground/background thresholds, identify objects, and plot.
nmask <- thresh(img, w=5, h= 15, offset= 0.05)
nmask <- opening(nmask, makeBrush(1, shape='line'))
nmask <- bwlabel(nmask)
plot(nmask)

#Generate data tables of object features and location in the image. 
#Create data frame with the area and circularity of each object in image to use for thresholding axon-like objects.
nmask_features <- data.frame(computeFeatures.shape(nmask))
nmask_moments <- data.frame(computeFeatures.moment(nmask))
nmask_feature_moment <- data.frame(nmask_features$s.area, nmask_moments$m.eccentricity)

#Remove objects that do not meet selection criteria for large enough axon-like objects and replot mask with only counted objects.
sel  <- which(nmask_feature_moment[, "nmask_features.s.area"] < 250)

xe <- rmObjects(nmask, sel)
plot(xe)

#Plot image depicting each axon-like object in a different color.
cols <- c('black', sample(rainbow(max(xe))))
zrainbow <- Image(cols[1+xe], dim=dim(xe))
plot(zrainbow)

#Create output pdf of original image.
pdf('Image.pdf')
plot(img)
dev.off()

#Create output pdf of masked image.
pdf('Image-Masked.pdf')
plot(xe)
dev.off()

#Create output pdf of masked image that has each object colored.
pdf('Object Identification.pdf')
plot(zrainbow)
dev.off()

#Determine the dimensions of the masked image.
nmask <- xe
dim(nmask)
width <- dim(nmask)[1]
height <- dim(nmask)[2]

#Create first of four intervals to count axon-like objects (at width/4 - ((width/4)/12)).
#Count number of axon-like objects in mask at first of four intervals, named "zero_obj."
#Create colored mask to identify individual objects in the area of interest.
x_2 <- width/4
x_2_2 <- x_2/12
x_2_2_2 <- x_2 - x_2_2
p1x2 <- img[1:x_2,]
zero_img <- xe[x_2_2_2:x_2,]
zero_stats <- data.frame(computeFeatures.shape(zero_img))
zero_obj <- nrow(zero_stats)
plot(zero_img)
cols = c('black', sample(rainbow(max(zero_img))))
zero_img_color <- Image(cols[1+zero_img], dim=dim(zero_img))
pdf('Zero_Img_color.pdf')
plot(zero_img_color)
dev.off()
plot(zero_img_color)

#Create second of four intervals to count axon-like objects (at width/2 - ((width/2)/12)).
#Count number of axon-like objects in mask at second of four intervals, named "second_obj."
#Create colored mask to identify individual objects in the area of interest.
y_2 <- width/2
y_2_2 <- (y_2 - x_2)/12
y_2_2_2 <- y_2 - y_2_2
p2y2 <- img[x_2:y_2,]
second_img <- xe[y_2_2_2:y_2,]
second_stats <- data.frame(computeFeatures.shape(second_img))
second_obj <- nrow(second_stats)
plot(second_img)
cols = c('black', sample(rainbow(max(second_img))))
Second_img_color <- Image(cols[1+second_img], dim=dim(second_img))
pdf('Second_Img_color.pdf')
plot(Second_img_color)
dev.off()
plot(Second_img_color)

#Create third of four intervals to count axon-like objects (at (3*width/4) - ((3*width/4)/12)).
#Count number of axon-like objects in mask at third of four intervals, named "third_obj."
#Create colored mask to identify individual objects in the area of interest.
z_2 <- (3*width/4)
z_2_2 <- (z_2 - y_2)/12
z_2_2_2 <- z_2 - z_2_2
p3z2 <- img[y_2:z_2,]
third_img <- xe[z_2_2_2:z_2,]
third_stats <- data.frame(computeFeatures.shape(third_img))
third_obj <- nrow(third_stats)
plot(third_img)
cols = c('black', sample(rainbow(max(third_img))))
Third_img_color <- Image(cols[1+third_img], dim=dim(third_img))
pdf('Third_Img_color.pdf')
plot(Third_img_color)
dev.off()
plot(Third_img_color)

#Create four of four intervals to count axon-like objects (at width - ((width)/12)).
#Count number of axon-like objects in mask at four of four intervals, named "fourth_obj."
#Create colored mask to identify individual objects in the area of interest.
zz_2 <- (width)
zz_2_2 <- (zz_2-z_2)/12
zz_2_2_2 <- zz_2 - zz_2_2
p4zz2 <- img[z_2:zz_2,]
fourth_img <- xe[zz_2_2_2:zz_2,]
fourth_stats <- data.frame(computeFeatures.shape(fourth_img))
fourth_obj <- nrow(fourth_stats)
plot(fourth_img)
cols = c('black', sample(rainbow(max(fourth_img))))
Fourth_img_color <- Image(cols[1+fourth_img], dim=dim(fourth_img))
pdf('Fourth_Img_color.pdf')
plot(Fourth_img_color)
dev.off()
plot(Fourth_img_color)

#Rename objects representing axon counts in each tissue section to interval names.
num_axon_section_0_500um <- zero_obj
num_axon_section_500_1000um <- second_obj
num_axon_section_1000_1500um <- third_obj
num_axon_section_1500_2000um <- fourth_obj

#Convert number of axons per tissue section to number of axons per nerve.
num_axon_nerve_0_500um <- round(3.14159*(0.3/2)^2*(num_axon_section_0_500um/0.3)/0.014)
num_axon_nerve_500_1000um <- round(3.14159*(0.3/2)^2*(num_axon_section_500_1000um/0.3)/0.014)
num_axon_nerve_1000_1500um <- round(3.14159*(0.3/2)^2*(num_axon_section_1000_1500um/0.3)/0.014)
num_axon_nerve_1500_2000um <- round(3.14159*(0.3/2)^2*(num_axon_section_1500_2000um/0.3)/0.014)

#Consolidate data for export.
Distance_from_injury_site <- c("0-500um", "500-1000um", "1000-1500um", "1500-2000um")
Number_axons_per_section <- c(num_axon_section_0_500um, num_axon_section_500_1000um, num_axon_section_1000_1500um, num_axon_section_1500_2000um)
Number_axons_per_nerve <- c(num_axon_nerve_0_500um, num_axon_nerve_500_1000um, num_axon_nerve_1000_1500um, num_axon_nerve_1500_2000um)

#Export data frame into an excel file that contains both number of axons per section & per nerve for each interval.
df <- data.frame(Distance_from_injury_site, Number_axons_per_section, Number_axons_per_nerve)
write_xlsx(df,paste0(title , "_Quantification.xlsx"))

